version: "3.4"

services:
  mongo:
    image: mongo
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: testpwd
    ports:
      - 27017:27017

  mongo-express:
    image: mongo-express
    restart: always
    ports:
      - 8081:8081
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: root
      ME_CONFIG_MONGODB_ADMINPASSWORD: testpwd
      ME_CONFIG_MONGODB_SERVER: mongo
    depends_on:
      - mongo
  tickets-backend:
    build: 
      context: .
      dockerfile: tickets-backend/Tickets/Dockerfile
    ports:
      - 5000:443
    environment:
      MongoDB__Host: mongo
      ASPNETCORE_ENVIRONMENT: Docker
      ASPNETCORE_URLS: https://+:443
      ASPNETCORE_Kestrel__Certificates__Default__Password: test123
      ASPNETCORE_Kestrel__Certificates__Default__Path: /https/aspnetapp.pfx
    volumes:
      - ~/.aspnet/https:/https:ro
    depends_on:
      - mongo
  client:
    build:
      context: .
      dockerfile: tickets-client/Dockerfile
    ports:
      - 3001:3000
    depends_on:
      - tickets-backend